# Generated by Django 5.2 on 2025-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='obrazki/')),
            ],
        ),
    ]
