# Generated by Django 5.2 on 2025-04-25 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapy', '0002_tlo_remove_choice_question_delete_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='obrazki/')),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Współrzędna X')),
                ('y', models.IntegerField(verbose_name='Współrzędna Y')),
                ('kolejnosc', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Punkt',
                'verbose_name_plural': 'Punkty',
                'ordering': ['trasa', 'kolejnosc', 'data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa trasy')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('obraz_tla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasy', to='mapy.background', verbose_name='Obraz tła')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasy', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Trasa',
                'verbose_name_plural': 'Trasy',
                'ordering': ['-data_modyfikacji'],
            },
        ),
        migrations.DeleteModel(
            name='Tlo',
        ),
        migrations.AddField(
            model_name='punkt',
            name='trasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty', to='mapy.trasa', verbose_name='Trasa'),
        ),
    ]
